# Generated by Django 4.0.5 on 2022-07-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionChainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField()),
                ('option_chain_symbol', models.CharField(max_length=10)),
                ('total_CE_OI', models.TextField(max_length=10)),
                ('total_PE_OI', models.TextField(max_length=10)),
                ('diff', models.TextField(max_length=10)),
                ('diff_pcr', models.TextField(max_length=10)),
                ('signal', models.BooleanField(default=False)),
            ],
        ),
    ]
