# Generated by Django 4.0.5 on 2022-07-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_oi_trace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionchaindata',
            name='diff',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='optionchaindata',
            name='diff_pcr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='optionchaindata',
            name='total_CE_OI',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='optionchaindata',
            name='total_PE_OI',
            field=models.CharField(max_length=10),
        ),
    ]
