# Generated by Django 4.0.5 on 2022-07-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc_oi_trace', '0002_alter_optionchaindata_diff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionchaindata',
            name='option_chain_symbol',
            field=models.CharField(choices=[('nifty', 'NIFTY'), ('banknifty', 'BANKNIFTY')], max_length=10),
        ),
    ]
